<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Peloton.Domain/Peloton.Domain.csproj" />
    <ProjectReference Include="../Peloton.Rules/Peloton.Rules.csproj" />
    <ProjectReference Include="../Peloton.Simulation/Peloton.Simulation.csproj" />
  </ItemGroup>
</Project>
